export const allProducts = [
  {
    id: 1,
    name: 'Designly UI',
    slug: 'designly-ui',
    tagline: 'Ready-made UI components for faster builds',
    description:
      'A growing library of modern, accessible UI components built for rapid product development.',
    websiteUrl: 'https://designlyui.example.com',
    tags: ['UI', 'Design', 'Frontend'],
    createdAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 6 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'ui@example.com',
    voteCount: 198,
  },
  {
    id: 2,
    name: 'LogWatch',
    slug: 'logwatch',
    tagline: 'Understand your logs without the headache',
    description:
      'Centralized log monitoring with powerful filters, alerts, and real-time insights for engineering teams.',
    websiteUrl: 'https://logwatch.example.com',
    tags: ['DevOps', 'Monitoring', 'Infrastructure'],
    createdAt: new Date('2024-02-01'),
    approvedAt: new Date('2024-02-02'),
    status: 'approved' as const,
    submittedBy: 'ops@example.com',
    voteCount: 264,
  },
  {
    id: 3,
    name: 'InvoiceMate',
    slug: 'invoicemate',
    tagline: 'Simple invoicing for freelancers',
    description:
      'Create, send, and track invoices effortlessly. Built for freelancers and small businesses.',
    websiteUrl: 'https://invoicemate.example.com',
    tags: ['Finance', 'Freelancer', 'SaaS'],
    createdAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 7 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'finance@example.com',
    voteCount: 143,
  },
  {
    id: 4,
    name: 'SpeedCheck',
    slug: 'speedcheck',
    tagline: 'Test and optimize your website performance',
    description:
      'Analyze page load times, core web vitals, and performance bottlenecks with actionable recommendations.',
    websiteUrl: 'https://speedcheck.example.com',
    tags: ['Performance', 'SEO', 'Web'],
    createdAt: new Date('2024-02-03'),
    approvedAt: new Date('2024-02-04'),
    status: 'approved' as const,
    submittedBy: 'seo@example.com',
    voteCount: 321,
  },
  {
    id: 5,
    name: 'NoteStack',
    slug: 'notestack',
    tagline: 'Organize your thoughts, effortlessly',
    description: 'A clean and fast note-taking app with markdown support, tags, and cloud sync.',
    websiteUrl: 'https://notestack.example.com',
    tags: ['Productivity', 'Notes'],
    createdAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 2 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'notes@example.com',
    voteCount: 176,
  },
  {
    id: 6,
    name: 'AuthShield',
    slug: 'authshield',
    tagline: 'Secure authentication for modern apps',
    description:
      'Plug-and-play authentication with support for OAuth, magic links, and multi-factor security.',
    websiteUrl: 'https://authshield.example.com',
    tags: ['Security', 'Authentication', 'Developer Tools'],
    createdAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 8 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'security@example.com',
    voteCount: 489,
  },
  {
    id: 7,
    name: 'ContentFlow',
    slug: 'contentflow',
    tagline: 'Plan and publish content at scale',
    description:
      'Collaborative content planning tool for marketing teams with workflows, approvals, and analytics.',
    websiteUrl: 'https://contentflow.example.com',
    tags: ['Content', 'Marketing', 'SaaS'],
    createdAt: new Date('2024-02-05'),
    approvedAt: new Date('2024-02-06'),
    status: 'approved' as const,
    submittedBy: 'content@example.com',
    voteCount: 207,
  },
  {
    id: 8,
    name: 'TestPilot',
    slug: 'testpilot',
    tagline: 'Automated testing without the complexity',
    description:
      'End-to-end testing platform that helps teams catch bugs early and ship with confidence.',
    websiteUrl: 'https://testpilot.example.com',
    tags: ['Testing', 'QA', 'Developer Tools'],
    createdAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 9 * 24 * 60 * 60 * 1000),
    status: 'approved' as const,
    submittedBy: 'qa@example.com',
    voteCount: 355,
  },
  {
    id: 9,
    name: 'HireLoop',
    slug: 'hireloop',
    tagline: 'Hiring pipelines made transparent',
    description:
      'Track candidates, manage interviews, and collaborate with your hiring team in one place.',
    websiteUrl: 'https://hireloop.example.com',
    tags: ['HR', 'Recruitment', 'SaaS'],
    createdAt: new Date('2024-02-07'),
    approvedAt: new Date('2024-02-08'),
    status: 'approved' as const,
    submittedBy: 'hr@example.com',
    voteCount: 189,
  },
  {
    id: 10,
    name: 'CloudSpend',
    slug: 'cloudspend',
    tagline: 'Take control of your cloud costs',
    description:
      'Monitor usage, detect anomalies, and optimize cloud spending across all your environments.',
    websiteUrl: 'https://cloudspend.example.com',
    tags: ['Cloud', 'FinOps', 'Analytics'],
    createdAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    approvedAt: new Date(Date.now() - 10 * 24 * 60 * 60 * 1000),
    status: 'pending' as const,
    submittedBy: 'cloud@example.com',
    voteCount: 92,
  },
];
